### ISSUE TITLE
Search: Glitchy behavior of search-as-you-type

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/addons#165]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/kedro/

## Expected Result

Search-as-you-type behaves normally.

## Actual Result

![Screen Recording 2023-10-18 at 13 36 10](https://github.com/readthedocs/readthedocs.org/assets/316517/c3d892f1-207f-42ae-839a-b385eaf4621a)

This is on both Firefox 118.0.2 and Safari on macOS Ventura. We just enabled the Addons.

cc @stichbury

**Comment by humitos** [comment]
Thanks for reporting this issue. I've moved it to the addons repository since this is related to the search addon.

Do you have a live example where I can see this behavior by myself? That will help me to debug this issue. I'm not sure to understand why the search as-you-type modal is shown when you click on that search input. We are not doing anything on purpose to connect that. In theory, the modal should be only shown when you click on the search input that it's _inside the flyout_ menu from Read the Docs, not on the search input from Sphinx. Maybe there their `id`s are duplicated?

**Comment by astrojuanlu** [comment]
> Do you have a live example where I can see this behavior by myself? 

Building: https://beta.readthedocs.org/projects/astrojuanlu-kedro-test/builds/22267498/

**Comment by astrojuanlu** [comment]
https://astrojuanlu-kedro-test.readthedocs.io/en/latest/ this page exhibits the same behavior (and also the `v:latest` part of the flyout looks really small, but that's a separate issue)

**Comment by astrojuanlu** [comment]
Keep us posted when this reaches production 🙏🏽

**Comment by humitos** [comment]
This issue is fixed and it's deployed. I'm not able to reproduce it anymore in https://astrojuanlu-kedro-test.readthedocs.io/en/latest/. Let me know if it works as expected 👍🏼

**Comment by astrojuanlu** [comment]
Now I see nothing (I click on the search bar or go there with `/`, and no modal pops up). Addons are enabled at the moment.

**Comment by humitos** [comment]
@astrojuanlu 

> Now I see nothing (I click on the search bar or go there with `/`, and no modal pops up).

This is by design. Our modal should only appears when clicking on our own UI [^1] or when the keyboard shortcut for `/` is not overwritten by the doctool itself [^2][^3]. We made this decision because it's pretty hard to integrate features on HTML/JS code that we don't control and we don't know what/how it could be. We learnt the lesson already and we are moving away from that 😄 

We decided to expose all our features/addons in a way that don't interfere with any HTML/JS code that could already exist in the page, as much as we can, and provide guiding for authors to be able to integrate those features in a "nicer way" with their doctool, theme, etc.

We haven't documented these integrations yet, but for the Sphinx case it would probably say something like the following, with some code examples [^4]:

1. disable Sphinx search keyboard `/` shortcut.
2. add a JS code to trigger the event `readthedocs-search-show` when `div[role=search] > form > input` gets focus.

This will protect ourselves from breaking people's documentation with new addons/features/changes, reduce the "magic" behind Read the Docs Addons and provide better integrations for more doctools that we may not be even aware of.

I'd love your feedback about these decisions and also I'd like to know if the search as you type works as it's expected in your site now 🙏🏼 

[^1]: clicking on the search input from the flyout should show the search as-you-type modal.
[^2]: Sphinx overwrites the `/` to capture it and put the focus on their own search input. You can disable it if you want by using the corresponding theme option. See config `enable_search_shortcuts` from Sphinx built-in themes: https://www.sphinx-doc.org/en/master/usage/theming.html#builtin-themes
[^3]: in fact, we are thinking about making the "hotkeys addon" opt-in by default due to this incompatibilities with different doctools that we already know they handle hotkeys by themselves.
[^4]: if you want to make this integration I can help you further with this.
