### ISSUE TITLE
Search: doesn't open after closing by clicking outside

### ISSUE THREAD

**Issue by humitos** [readthedocs/addons#169]
Steps to reproduce:

- hit `/` to open the search modal
- click outside the modal to close it
- hit `/` again
- it does not open as expected

This is because the state saved inside the `hotkeys.js` file is not updated when clicking outside.

**Comment by humitos** [comment]
I suppose that the action "clicking outside the modal" (at https://github.com/readthedocs/readthedocs-client/blob/6ecc7525c3ce085e69ae515fa6c592011633396c/src/search.js#L113) should trigger the event `EVENT_READTHEDOCS_SEARCH_HIDE` that should be catched by the `hotkeys.js` addon and update its state regarding that.

Another alternative could be a way to globally check if the `readthedocs-search` tag is visible or by inspecting the DOM.

**Comment by humitos** [comment]
I did something similar in #247 if you want to have a related example for this.

**Comment by zanderle** [comment]
> the action "clicking outside the modal" should trigger the event EVENT_READTHEDOCS_SEARCH_HIDE that should be catched by the hotkeys.js addon and update its state regarding that.
> Another alternative could be a way to globally check if the readthedocs-search tag is visible or by inspecting the DOM.

Those are both valid solutions. However I'm wondering if we even need the requirement that the same hotkey both opens AND closes the modal? Since we already use Escape to close the modal, do we need to close it with `/` as well? If not, we could have `hotkeys.js` always fire `EVENT_READTHEDOCS_SEARCH_SHOW` when the hotkey is pressed, and let the search modal simply ignore the event, if it's already opened.

**Comment by humitos** [comment]
@zanderle yeah, we don't need to use the same key to open _and_ close. `/` should open it and `Esc` should close it.
