### ISSUE TITLE
Flyout: tiny size due to small root element `font-size`

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/addons#175]
| Old (without addons)                                                                                                                                                                           | New (with addons)                                                                                                                                                                              |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| ![Old (without addons)](https://github.com/readthedocs/addons/assets/316517/660e0631-a3f8-43b3-84b1-8fcaa3c11d8b) | ![New (with addons)](https://github.com/readthedocs/addons/assets/316517/f5856106-8466-4460-8189-2eff89fcbde4) |

https://astrojuanlu-kedro-test.readthedocs.io/en/latest/ (you can test enabling/disabling addons)

This is on my laptop (1512x982), on a larger screen the effect is much more noticeable (exacerbated by https://github.com/readthedocs/sphinx_rtd_theme/issues/295 of course)

**Comment by humitos** [comment]
This is tricky. We have a similar issue with Material for MkDocs at https://github.com/readthedocs/addons/issues/95 that shows it a little bigger than it should be.

In this case, the reason is that the "global CSS `font-size` property" is small than _100%_ (which is the normal value) for some reason. As Read the Docs flyout uses `0.8 rem` [^1] and `0.9 rem` to make the font a little smaller than the global size, the flyout is rendered smaller than it should be.

I checked your documentation and, in your case, it's re-defining `html { font-size: 70% }` or `html { font-size: 62.5% }` depending on the screen size (see https://github.com/kedro-org/kedro/blob/main/docs/source/_static/css/qb1-sphinx-rtd.css#L70 and https://github.com/kedro-org/kedro/blob/main/docs/source/_static/css/qb1-sphinx-rtd.css#L14).

You should adapt your theme to make usage of `font-size: 100%` on the root element, and reduce the font only on those elements you want a smaller font size.

Unfortunately, this is something we don't have control over and we can't do too much here.

[^1]: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units#relative_length_units

**Comment by humitos** [comment]
We've added the ability to overwrite a CSS variable to change the `font-size` of the Read the Docs flyout. I'd suggest you to follow this approach once it's merged and released since it's a lot simpler than modifying your whole Sphinx theme. See https://github.com/readthedocs/addons/pull/181 🎉
