### ISSUE TITLE
Docdiff should not apply the 'd' hotkey in textareas

### ISSUE THREAD

**Issue by davidfischer** [readthedocs/addons#205]
Docdiff doesn't apply the `d` hotkey when typing in `<input>` fields but should apply similar checks to `<textarea>` fields.

https://github.com/readthedocs/addons/blob/ff8baf238d4734152dc2373afac0757a4dc7c6f5/src/hotkeys.js#L49-L69

You can see this bug in the [notes field](https://www.ethicalads.io/publishers/#inbound-form) on ethicalads.io where the 'd' character cannot be typed.

**Comment by astrojuanlu** [comment]
We're still spotting this https://github.com/kedro-org/kedro/pull/3371#issuecomment-1833810640

**Comment by humitos** [comment]
@astrojuanlu thanks for commenting here pointing out to a reproducible example. I think the issue you are hitting similar to the one this issue mentions and it was solved in `v0.9.0` by this PR of the addons which I released the past Tuesday but I had to revert that deploy because it broke other stuffs 😅  (see https://github.com/readthedocs/addons/issues/207)

I double checked the code and it seems it's correct: https://github.com/readthedocs/addons/blob/main/src/hotkeys.js#L58-L63

Once I fix the 0.9.0, I will do another one that once deployed it _should_ solve the issue you are experimenting. I'm targeting this release to next Tuesday. If you want, I can disable the "hotkeys addons" in your project now as an immediate workaround. Let me know.

I'll keep you posted otherwise 👍🏼

**Comment by astrojuanlu** [comment]
Thanks! cc @rashidakanchwala

**Comment by humitos** [comment]
I just merged #208 which solves the issue with the previous release and I've deployed 0.9.1 with the fix for this. I just tested your project at https://rashida-test-kedro.readthedocs.io/en/latest/ and I was able to type the `d` letter without problem when performing a search 😄 

I'd appreciate any other feedback you may have in the future 🙏🏼
