### ISSUE TITLE
Confusing toggles in search-as-you-type modal

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/addons#209]
What's the difference between "search only in this project" and "search subprojects"? Shouldn't there be only one option?

![image](https://github.com/readthedocs/addons/assets/316517/aa1f8cd4-06a7-4455-a8b2-c29049e498a7)

(Also, the "filters" positioning might need some CSS sprinkles)

**Comment by humitos** [comment]
Thanks for beta testing addons and reporting this! 👍🏼 

I opened https://github.com/readthedocs/readthedocs.org/pull/10951 to solve this. Please, let me know if that approach makes more sense to you.

> (Also, the "filters" positioning might need some CSS sprinkles)

This is due to a custom CSS value you have in your project. We are thinking in a simple/global way to update CSS variables to keep these proportions clean in https://github.com/readthedocs/addons/issues/197. We will need to do something similar to `readthedocs-flyout-font-size` for all the addons. That variable should affect not only `font-size` but padding and other CSS properties as well.
