### ISSUE TITLE
Search: default Sphinx search doesn't work on older versions after enabling addons; changes format of flyout

### ISSUE THREAD

**Issue by jillnogold** [readthedocs/addons#220]
- The [fix for Search with addons enabled](https://github.com/readthedocs/addons/issues/213) works after rebuilding a version. However there are versions that cannot be rebuilt due to updates in readthedocs. How to enable the version warning in older versions?
- After enabling addons, the flyout moves to the lower-right corner, and lists the versions in the reverse order. How do I keep the previous format?
- The warning opens on every page. Can it be configured to open only on the first page of a release?

**Comment by humitos** [comment]
Hi! 👋🏼  Thanks for opening this issue.

> The [fix for Search with addons enabled](https://github.com/readthedocs/addons/issues/213) works after rebuilding a version. However there are versions that cannot be rebuilt due to updates in readthedocs. How to enable the version warning in older versions?

The old version warning cannot be enabled on older versions. That feature was deprecated some time ago due to its inconsistencies and UX confusions and because it was re-written into the new addons with a simpler logic for a specific use-case more aligned with Read the Docs' `latest` and `stable` versions, that doesn't guess on the versioning schema the project uses.

The "old version warning" is only available for those projects that were already using it at the time of the deprecation. However, if you are using the new beta addons, it's not possible to enable the "old version warning" feature since they are incompatible each other.

Just for reference, the issue about not being able to rebuild an old version due Read the Docs changes is related to #219 too.

> After enabling addons, the flyout moves to the lower-right corner, and lists the versions in the reverse order. How do I keep the previous format?
> The warning opens on every page. Can it be configured to open only on the first page of a release?

Currently, we don't allow customization of the addons. However, we plan creating a new page under the project's admin for these customization. See https://github.com/readthedocs/ext-theme/issues/211 for more information and feel free to share your feedback there as well.

**Comment by humitos** [comment]
> The warning opens on every page. Can it be configured to open only on the first page of a release?

We have thought about a similar approach in https://github.com/readthedocs/addons/issues/46. Can you share your thoughts there? Thanks!

**Comment by jillnogold** [comment]
@humitos Seems that I misunderstood the fix https://github.com/readthedocs/addons/issues/213. I enabled the **beta addons**, and it broke the search unless I rebuilt the various versions (not all of which can be rebuilt).
Ot did I misunderstand your response?

**Comment by humitos** [comment]
> I enabled the **beta addons**, and it broke the search unless I rebuilt the various versions (not all of which can be rebuilt).

Yes. It currently requires a rebuild of the version. See #219. I put a fix for this already, but it's under review still. I can probably deploy it next week if everything goes fine.

**Comment by humitos** [comment]
@jillnogold Hi 👋🏼 ! Can you share the URL of your project on Read the Docs? I just deployed a fix and I want to test it with your project.

**Comment by jillnogold** [comment]
@humitos sure - it's https://docs.mlrun.org/en/stable/
I just re-enabled the addons.

**Comment by humitos** [comment]
@jillnogold cool, thanks! It seems it works fine now: https://docs.mlrun.org/en/stable/search.html?q=graphserver

**Comment by humitos** [comment]
Great! I'm happy it's working.

> But I am seeing some duplication in search results, though it's only for some hints

What's the URL for that search? This is probably just Sphinx not being super smart with the search index/query/results.

**Comment by jillnogold** [comment]
@humitos I had to disable the addons - the Search works in all releases I tested except stable

**Comment by jillnogold** [comment]
@humitos On Monday the search worked in stable.  But on Tuesday, when I tried searching, the main page was blank. Searching in latest and in earlier versions produced results.  I can't leave stable without search results, so had to disable the addons

**Comment by humitos** [comment]
OK, thanks! Let me know when you're ready to enable addons on your docs so I can debug that further and fix the issues.

**Comment by jillnogold** [comment]
@humitos Can we set a 1-2 hour window for you to debug, to  minimize the disruption of **stable**?
What timezone/hours are good for you?
