### ISSUE TITLE
Flyout: sort by version number, not lexicographically

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/addons#222]
Right now versions are sorted in alphabetical/lexicographical order, which produces some funny results

![image](https://github.com/readthedocs/addons/assets/316517/805118d9-eb03-4a80-a7b6-5ffb7676a739)

**Comment by humitos** [comment]
I made the decision of sorting the version alphabetically by default on purpose. This is mainly to have a pretty simple and well defined sorting algorithm that everybody can easily understand.

In the old flyout, we use a pretty custom sorting algorithm that almost nobody understands, has lot of edge cases, and it's not possible to change without breaking people's documentation. I'm trying to avoid this pattern in the new flyout implementation.

This is the code of the "custom sorting algorithm" ™️ :

* https://github.com/readthedocs/readthedocs.org/blob/43423855edd0012ccd20d8bd3cd0402b46b2b41c/readthedocs/api/v2/views/footer_views.py#L138
* https://github.com/readthedocs/readthedocs.org/blob/43423855edd0012ccd20d8bd3cd0402b46b2b41c/readthedocs/projects/models.py#L1110
* https://github.com/readthedocs/readthedocs.org/blob/43423855edd0012ccd20d8bd3cd0402b46b2b41c/readthedocs/projects/templatetags/projects_tags.py#L12
* https://github.com/readthedocs/readthedocs.org/blob/43423855edd0012ccd20d8bd3cd0402b46b2b41c/readthedocs/projects/version_handling.py#L49

My idea is to make the sorting algorithm configurable via https://github.com/readthedocs/ext-theme/issues/211 by exposing different sorting options to users, making each of them as clear as possible to manage different use cases (e.g. alphabetically, CalVer, SemVer, etc).

I don't know _when_ this is going to be available, but I remember having issues on the logic for SemVer when working on the notifications addon at https://github.com/readthedocs/addons/issues/71 and that's why I ended up implementing a pretty basic "is `latest` or non-`stable`" logic for that addon. Hopefully, we can find a way to make SemVer _as simple as it seems_ without unexpected behaviors.

That said, I'd appreciate any feedback anyone can provide here. I will take it into consideration when jumping into this work 👍🏼

**Comment by humitos** [comment]
Interesting. While doing some research about how to implement this, I found that depending on the PEP440 pattern you choose, it may be possible to sort it lexicographically or not: https://github.com/mbarkhau/bumpver#pattern-examples

**Comment by humitos** [comment]
I opened a PR for this and I'd appreciate any feedback you may have about it: https://github.com/readthedocs/readthedocs.org/pull/11069. It implements different sorting algorithms and let the user to choose between them or create their own if required.

**Comment by astrojuanlu** [comment]
I didn't forget about this 🙏🏽

**Comment by humitos** [comment]
@astrojuanlu Thanks for the ping. Everything is on its place. The [PR is waiting for a final review](https://github.com/readthedocs/readthedocs.org/pull/11069). Hopefully, it will be deployed next Tuesday.

**Comment by humitos** [comment]
A feature to sort versions in the beta addons flyout was released today. To enable this feature, you will need to activate the new beta addons in your project first, and then edit the sorting from the project's setting using the new beta dashboard from https://beta.readthedocs.org/. Please, let me know any feedback you may have 🙏🏼 

![Screenshot_2024-03-12_16-36-16](https://github.com/readthedocs/readthedocs.org/assets/244656/846146ad-5b30-4240-9d08-901ef56232df)

**Comment by astrojuanlu** [comment]
| Before | After |
|--------|-------|
| ![Screenshot 2024-03-17 at 15-44-57 Welcome to Kedro’s award-winning documentation! — kedro 0 19 3 documentation](https://github.com/readthedocs/addons/assets/316517/091b54ba-2fb9-45ec-8840-fafffbd930de)   | ![Screenshot 2024-03-17 at 15-45-09 Welcome to Kedro’s award-winning documentation! — kedro 0 19 3 documentation](https://github.com/readthedocs/addons/assets/316517/2c4be33a-f52f-4bf2-96f9-193b9467ec24)  |

Thank you ❤️
