### ISSUE TITLE
Search: arrow keys navigation is inconsistent and skips entries

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/addons#316]
The navigation by arrow keys is not what I would expect, I can't tell what the pattern to movement is actually:

[Screencast from 2024-05-21 19-53-57.webm](https://github.com/readthedocs/addons/assets/1140183/73fbc946-abbf-444b-a263-bb85a60d058d)

**Comment by zanderle** [comment]
I believe it's because we're not correctly creating unique IDs for the hits: https://github.com/readthedocs/addons/blob/eae31c8e37d5c62f297486260d6f3a80ec00f705/src/search.js#L263 which is used here: https://github.com/readthedocs/addons/blob/eae31c8e37d5c62f297486260d6f3a80ec00f705/src/search.js#L307

Should be an easy fix.
