### ISSUE TITLE
Rename library

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/addons#4]
Before we start using this on user projects/publicly, `readthedocs-client`
sounds like a CLI or API wrapper, and we've called this the doc embed JS so
far. There's probably wisdom is reusing that naming or something similar.

**Comment by agjohnson** [comment]
Good points! I like something like `readthedocs-tools`, though that has overlap with build tools :upside_down_face: 

I think `readthedocs/doc-tools` or `readthedocs/doc-utils` are good targets. I like the narrative of "things we add to your documentation to make it better".

I've been throwing these types of questions to OpenAI and tune the outputs. It gave some good ideas:

- readthedocs-tools
- doc-utilities
- readthe-utils
- rtd-helpers
- readthedocs-helpers
- doc-helpers
- doc-tools
- document-tools
- readthedocs-utilities
- document-utilities
- document-helpers
- rtd-utilities
- documentation-tools
- readthedocs-resources
- doc-resources
- readthedocs-support
- documentation-utilities
- documentation-helpers

**Comment by humitos** [comment]
> I like the narrative of "things we add to your documentation to make it better".

Yes, yes, yes! I've been thinking think for a while now, since I wrote https://github.com/readthedocs/reports/pull/20#discussion_r1042075502 when talking about the 2023 roadmap 💯 

✨`make-my-docs-better.js` 😅 

In fact, how much marketing-y we want to go? What about something like `readthedocs-superpowers.js` or something similar in that direction?

**Comment by agjohnson** [comment]
Hah, I was also thinking of something goofy like that, I'm definitely not opposed!

**Comment by agjohnson** [comment]
Me and the AI went off the rails a bit, but it gave a few fun ideas:

- doc-powerups
- doc-booster
- doc-juice
- doc-sauce
- doc-magic
- doc-boost

:upside_down_face: 

There is definitely a product discussion in here though, and probably not something we need to consider just yet, but it is great to keep this in mind for later. We need to determine if we will be using _injection of a group of features into documentation_ as a marketable feature, or is what we're marketing the individual features and injection is merely a technical implementation detail.

I might lean a bit towards the latter right now, but I do think we'll need some language for _the group of features that we are inject_.

**Comment by benjaoming** [comment]
readthedocs-embed-client or readthedocs-embed-client-js ?

**Comment by benjaoming** [comment]
I think I like `readthedocs-integrations` or `readthedocs-helpers` most of all the current candidates. They carry a certain aspect of the potentially UI-heavy aspect of the library. Since its for online websites, it could be called `readthedocs-web-integrations`

If called `readthedocs-helpers`, I could see spinoffs like `readthedocs-helpers-sphinx` and `readthedocs-helpers-mkdocs`.

**Comment by humitos** [comment]
@benjaoming 

> readthedocs-helpers most of all the current candidates

@agjohnson 

> I think readthedocs/doc-tools or readthedocs/doc-utils are good targets

I'd prefer to not use things like `helpers`, `utils`, `tools` or similar. Those names usually convey the meaning "I'm not sure where to put this function, so let's create a utils file" 😄 

>If called readthedocs-helpers, I could see spinoffs like readthedocs-helpers-sphinx and readthedocs-helpers-mkdocs.

We should not have files for specific doctools, since the idea is to be agnostic regarding to that.

----

The more I think about this, the more I like something like `readthedocs-superpowers.js` which communicates it's about Read the Docs, it gives some extra power/features to your site and it's a good marketing name, IMO.

I think I will move forward with it unless you are oppose on that.

**Comment by benjaoming** [comment]
I didn't think that `readthedocs-superpowers` is a thaaat good as a name :) I know that we know the complexity involved in it and why it's great. But for a small menu in a corner, the feeling of "underwhelmed" might occur :)

If you get your superpowers from mate, then I like `readthedocs-mate`... people that know the drink will think "juice" and people that read it as Australian will see it as a companion, which is also a really good name :) + the emoji exists :) It's a bit abstract, but it seems that the exact scoping of what the library does has made it hard to choose a normal name.

---

> Those names usually convey the meaning "I'm not sure where to put this function, so let's create a utils file" smile

I think it fits very well with what this library is? A home for all client-side *stuff*? Do you worry that functionality that isn't at home in the library would end up here?

Because otherwise I think this is what it is: A lot of utility/helper functionality with no distinct theme. Some of it does UI, some of it does API calls, some of it is related to version logic, some of it is related to toggling the diff viewer.. lots of stuff!

> We should not have files for specific doctools, since the idea is to be agnostic regarding to that.

It was a bad example to show that the naming convention looks nice if you want to have an extension, but no I agree that we will have a hard time maintaining multiple libraries, so it's nice to just have 1 library for everything :+1: 

---

`readthedocs-menu` would be another suggestion.. just to say what it is in the bigger picture. Most people can understand this as the library that inserts the menu. Everything else can seem secondary?

**Comment by agjohnson** [comment]
Great question, this is one of the remaining points I'm not yet settled on. I guess I was suggesting `Doc Addons` as a feature name, `doc-addons` the library/repo/etc name. But probably only because it's a little bit more clear what function the addons serve -- they add on to docs, as opposed to add on to _something undefined_.

But that's just a guess too. Do others pull the same interpretation from just "Addons"?

**Comment by benjaoming** [comment]
I would think that prefixing with `readthedocs` makes it more clear what the library is really doing, i.e. connecting to RTD APIs. I would worry that `doc-addons` is really generic and would make it look like it's not a Read the Docs specific thing... but it is? :)

**Comment by benjaoming** [comment]
Also not completely impossible to call it `readthedocs-doc-addons` but then there's the docs-doc confetti, which is too silly :)

**Comment by agjohnson** [comment]
When we add HTTP proxy support for injecting HTML snippets it could be called `readthedocs-docs-socks-blocks-addon` :joy: 

>  I would worry that doc-addons is really generic

I guess to elaborate:

- `readthedocs/docs-addons` - repo here
- `@readthedocs/docs-addons` - npm package name
- `readthedocs-docs-addons.js` - web bundle name
- etc

**Comment by ericholscher** [comment]
I think we arrived at Addons for the name here -- I say we should probably rename this library here soon, so we can start using it properly!

**Comment by humitos** [comment]
> * `readthedocs/docs-addons` - repo here
> * `@readthedocs/docs-addons` - npm package name
> * `readthedocs-docs-addons.js` - web bundle name


@agjohnson @ericholscher are we OK with these names? I can do the rename if so.

**Comment by agjohnson** [comment]
Yeah, those names are good still I feel. If anyone has strong opinions otherwise, my main concern is mentioning `addons` and using the same name everywhere, give or take a symbol or two.

**Comment by ericholscher** [comment]
Any reason not to just say `readthedocs/addons`? Not sure if the `docs` is adding much?

**Comment by agjohnson** [comment]
Aye, I had the same thought above and don't feel strongly either way

- readthedocs/addons - repo here
- @readthedocs/addons - npm package name
- readthedocs-addons.js - web bundle name

That seems solid as well :+1:

**Comment by humitos** [comment]
> readthedocs/addons - repo here

✔️ 
 
> @readthedocs/addons - npm package name

I created the `readthedocs` organization at https://www.npmjs.com/org/readthedocs

> readthedocs-addons.js - web bundle name

* PR at #74 here
* PR in org at https://github.com/readthedocs/readthedocs.org/pull/10531
* PR in ops at https://github.com/readthedocs/readthedocs-ops/pull/1372

I also re-upload the js file as https://readthedocs-static-prod.s3.us-east-2.amazonaws.com/javascript/readthedocs-addons.js

I think we have everything in place now.

**Comment by ericholscher** [comment]
Awesome -- I'm glad we're using the same name in the code as in the marketing, that always helps make it easier to understand and communicate. 👍

**Comment by agjohnson** [comment]
> I created the readthedocs organization at https://www.npmjs.com/org/readthedocs

@humitos I think this invite doesn't work for me because my NPM account is using my personal info. Could you send to NPM user agjohnson or agjohnson@protonmail.com?

**Comment by humitos** [comment]
@agjohnson done!

**Comment by agjohnson** [comment]
Hrm, actually, it was the same effect: "Invitation was revoked" :shrug: 

![image](https://github.com/readthedocs/addons/assets/1140183/38aa3120-097a-454e-9059-eb12ff90e30b)

I'll note to bug you about this again when I'm back, it's not really critical at all. In fact, I mostly think we'll just use the namespacing while internally working with the packages, but perhaps there will be a time we install everything through NPM

**Comment by pradyunsg** [comment]
FWIW, as an outside of group collaborator-ish person, I like this new name (and +1 on the naming consistency as well)!
