### ISSUE TITLE
Flyout: font is bigger on Material for MkDocs

### ISSUE THREAD

**Issue by humitos** [readthedocs/addons#95]
Sites using Material for MkDocs has a flyout with a bigger font: https://docs.pypi.org/

![Screenshot_2023-08-30_11-43-52](https://github.com/readthedocs/addons/assets/244656/72a86c0b-c312-4170-a1e6-6e98af7f41dd)

Other sites show the flyout as we want: https://pycamp.es/

![Screenshot_2023-08-30_11-44-14](https://github.com/readthedocs/addons/assets/244656/21a5e515-7df6-486c-a036-e805aecb21ae)

**Comment by humitos** [comment]
The notification has the same issue 

![Screenshot_2023-09-06_14-09-28](https://github.com/readthedocs/addons/assets/244656/f227462b-1e17-45f3-bee2-522abecabed7)

Example: https://vizro--6.org.readthedocs.build/en/6/

**Comment by zanderle** [comment]
> Yes. I think the flyout should be _the same_ no matter who the page looks like. What do you think?

I think both options are valid. But I'll go with yours :)

**Comment by humitos** [comment]
> For example, it would be great if we could just set the `font-size: 16px;` on the root of the component, and have our `rem` units depend on that. But that won't work.

I don't understand why this won't work. Can you expand on that?

>  Keep using `rem` and let the users override these with css variables (which we are already doing). This means that if the parent html is using a bigger root `font-size` (like for example [docs.pypi.org](https://docs.pypi.org/)), the font-size in our components will be bigger as well. But the user can make it smaller, by defining the appropriate css variables.

Ideally, IMO, the user shouldn't define the `font-size` to make the flyout font a little smaller when using Material for MkDocs. We have a lot of projects using this theme and I'd like our flyout to look exactly the same in all of those without each of the projects to define this variable.

I think the flyout should look exactly the same across all the projects and doctools: Sphinx, MkDocs, Docusarus, Pelican, etc. So, if it's possible to the define "the font-size on the root of the component and keep using `rem` from there" that would be amazing.

**Comment by zanderle** [comment]
> > For example, it would be great if we could just set the `font-size: 16px;` on the root of the component, and have our `rem` units depend on that. But that won't work.
> 
> I don't understand why this won't work. Can you expand on that?
> 

It's because `rem` will always look at the root element, which is the parent html. It doesn't consider the root of the Shadow DOM.

**Comment by zanderle** [comment]
@humitos so we're going with

> Stop using rem in the web components. Instead use px or em. However using em can be tricky when it comes to nesting. Users can still override these with appropriate css variables, so they can change the sizes if they want.

right?

**Comment by humitos** [comment]
I want to loop @agjohnson in here since I'd probably vote for `px` or `em` due to this issue. However, I think he is the one that knows more here and may have a different opinion.

**Comment by agjohnson** [comment]
Hrm, so this is getting into a bit of a tricky place.

While I'd tend to agree it would be great to retain a single effective styling to the flyout, using `px/em` instead of a relative unit creates problems for the reader user. 

The biggest issue is that using `px` will override not just the root `font-size`, it will also override *any user preference for font size on a reader's browser or monitor as well*.

[This is a good article outlining why this is a pattern to avoid](https://www.aleksandrhovhannisyan.com/blog/use-rems-for-font-size/).

I would say I'd agree with @zanderle that the first option, always using `rem`, provides the best experience to the reader user and most documentation tool users -- especially considering this is only Material for MkDocs so far. There are probably more themes/tools that will make similar font-size changes, but it might have to be a widespread problem before I feel it would warrant removing the reader user's ability to change the font-size.

Unfortunately there aren't great compromises here. We either remove control from the reader user, or we put the onus on the documentation tool/theme authors to integrate with Read the Docs. Given this is already our stance on build configuration, I think its reasonable to expect the tools/theme authors to ensure their CSS styles don't impact the flyout negatively. I'll also say that this isn't the most ideal answer, but it's consistent with our plans overall. 

I will say that one thing we could be doing better with is that we have been mixing absolute and relative units in our CSS. If we stuck to `rem` for every measurement, then elements would at least scale with the theme/browser/monitor font size. At least the flyout would look in proportion in this case, as opposed to have a 16px logo but a 32px font for example.

**Comment by zanderle** [comment]
Ok, so you're saying we should go with `rem`, but go over the styles to make sure they're used consistently? @agjohnson 

That sounds like a good approach to me, even with the issues that this brings.

**Comment by agjohnson** [comment]
Or at very least, we proceed with what you mentioned and stay with `rem` units for now. Standardizing *all units* on `rem` is maybe solving a slightly different issue.

I figured I'd mention this in case our concern isn't just *that the font size is bigger*, but instead more specifically is *the flyout/etc looks out of proportion when the font-size is increased*. This is probably true, but only will be noticeable at some extremes, when border-radius, logo/icon height, etc doesn't scale the `px` unit with a larger `rem` unit.

And even still, there are some units that always make more sense as `px` -- border-width, etc. I'm also not opposed to some `calc()` math either.

**Comment by ericholscher** [comment]
Call notes: There is not an obvious next step here, since there isn't an obvious technical solution here.

**Comment by zanderle** [comment]
Maybe the next step here is to document all the various css variables that users can use to change the font sizes of specific items in the flyout. We have `--readthedocs-flyout-font-size`, `--readthedocs-flyout-header-font-size`, `--readthedocs-flyout-dt-font-size` and `--readthedocs-flyout-dd-font-size`. Currently these are completely independent from each other. But maybe for easier usage we could also replace these with `calc` instead - that way we could have a single variable that the user can adjust (for example `--readthedocs-flyout-font-size`) and everything else is calculated based on that (unless a specific font-size is specifically set - then that can take precedence. 

So for example for specific section headline we could have:

```css
dl > dt {
  font-size: var(--readthedocs-flyout-dt-font-size, calc(var(--readthedocs-flyout-font-size, 1rem) * 0.9));
}
```

Which will look at `--readthedocs-flyout-dt-font-size` for the font-size, if possible. If not, it will take a look at `--readthedocs-flyout-font-size` and take 90% of that value (the specific values would need to be adjusted for this to work, of course).
That way the user can change the font-sizes of the whole flyout with just one variable, but can also change specific items, if they want.

**Comment by agjohnson** [comment]
That would be a great addition, it's a good balance between easy and advanced control of the styles.

**Comment by zanderle** [comment]
Ok, I'll prepare a PR as a POC

**Comment by humitos** [comment]
> But maybe for easier usage we could also replace these with `calc` instead - that way we could have a single variable that the user can adjust (for example `--readthedocs-flyout-font-size`) and everything else is calculated based on that (unless a specific font-size is specifically set - then that can take precedence.

This would be great!

Communicating these CSS variables to users will be a lot easier to force them to change the root `font-size` as I told them at https://github.com/readthedocs/addons/issues/175#issuecomment-1781389315

**Comment by zanderle** [comment]
Ok, here's the POC: https://github.com/readthedocs/addons/pull/181
